name: pontogov_services_dev

services:
  postgres_db:
    extends:
      file: ./backend/server/docker-compose.dev.yml
      service: postgres_db
    networks:
      - pontogov_network

  server_api:
    extends:
      file: ./backend/server/docker-compose.dev.yml
      service: server_api
    depends_on:
      - postgres_db
    networks:
      - pontogov_network

  admin_frontend:
    extends:
      file: ./frontend/admin/docker-compose.yml
      service: admin_frontend
    networks:
      - pontogov_network

volumes:
  postgres_db_data:

networks:
  pontogov_network:
