name: pontogov_services

services:
  postgres_db:
    image: postgres:16
    container_name: postgres_db
    env_file:
      - ./backend/server/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    networks:
      - pontogov_network

  server_api:
    build:
      context: ./backend/server
    container_name: server_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    env_file:
      - ./backend/server/.env
    networks:
      - pontogov_network
    volumes:
      - ./backend/server:/app
      - ~/.m2:/root/.m2

  admin_frontend:
    build:
      context: ./frontend/admin
    container_name: admin_frontend
    ports:
      - "4200:4200"
    depends_on:
      - server_api
    volumes:
      - ./frontend/admin:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - pontogov_network

volumes:
  postgres_db_data:

networks:
  pontogov_network:
