name: pontogov_backend_services

services:
  postgres_db:
    image: postgres:16
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    networks:
      - pontogov_network

  server_api:
    build: .
    container_name: server_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    env_file:
      - .env
    networks:
      - pontogov_network
    volumes:
      - .:/app
      - ~/.m2:/root/.m2

volumes:
  postgres_db_data:

networks:
  pontogov_network: