name: pontogov_backend_services_prod

services:
  postgres_db:
    image: postgres:16
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - pontogov_network
    volumes:
      - postgres_db_data:/var/lib/postgresql/data

  server_api:
    build: .
    container_name: server_api
    depends_on:
      - postgres_db
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - pontogov_network

volumes:
  postgres_db_data:

networks:
  pontogov_network: