name: pontogov_frontend_services

services:
  admin_frontend:
    build: .
    container_name: admin_frontend
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true